module BackendTest;

exception MyException(Int, Bool);
{
  Int x=0;
  Bool testresult = False;
  try {
    x = x + 1;
    throw MyException(x, True);
    x = x + 100;
  } catch {
    MyException(0,False) => skip;
    MyException(1,False) => skip;
    MyException(1,True) => { x=x+1; x = x + 2; }
  }
  finally {
    x=x+1;
  }
  testresult = (x == 5);
}